import { describe, expect, it } from "vitest";

import { normalizeHex, setPowerShellTabColor } from "./jsonc-profile-patch";

const WITH_COMMENTS = `// This file was initially generated by Windows Terminal.
{
    "$help": "https://aka.ms/terminal-documentation",
    "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
    "profiles":
    {
        "defaults": {},
        "list":
        [
            {
                // The stock Windows PowerShell entry.
                "commandline": "%SystemRoot%\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe",
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "hidden": false,
                "name": "Windows PowerShell"
            },
            {
                "commandline": "%SystemRoot%\\\\System32\\\\cmd.exe",
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "hidden": false,
                "name": "Command Prompt"
            }
        ]
    },
    "schemes": [],
    "themes": []
}
`;

describe("setPowerShellTabColor", () => {
  it("inserts tabColor on the Windows PowerShell profile and leaves the rest alone", () => {
    const patched = setPowerShellTabColor(WITH_COMMENTS, "#2f5f87");
    expect(patched).not.toBeNull();
    expect(patched).toContain(`"tabColor": "#2F5F87"`);
    // Comments survive.
    expect(patched).toContain("// This file was initially generated by Windows Terminal.");
    expect(patched).toContain("// The stock Windows PowerShell entry.");
    // Exactly one line differs.
    const before = WITH_COMMENTS.split("\n");
    const after = patched!.split("\n");
    expect(after.length).toBe(before.length + 1);
    expect(after.filter((line) => !before.includes(line))).toEqual([`                "tabColor": "#2F5F87",`]);
    // Still parses once comments are stripped.
    expect(() => JSON.parse(patched!.replace(/^\s*\/\/.*$/gm, ""))).not.toThrow();
  });

  it("does not touch the Command Prompt profile", () => {
    const patched = setPowerShellTabColor(WITH_COMMENTS, "#2f5f87")!;
    const cmdIndex = patched.indexOf("Command Prompt");
    const cmdBlock = patched.slice(patched.lastIndexOf("{", cmdIndex), cmdIndex);
    expect(cmdBlock).not.toContain("tabColor");
  });

  it("replaces an existing tabColor rather than adding a second", () => {
    const withColor = WITH_COMMENTS.replace(
      `"hidden": false,\n                "name": "Windows PowerShell"`,
      `"hidden": false,\n                "name": "Windows PowerShell",\n                "tabColor": "#111111"`,
    );
    const patched = setPowerShellTabColor(withColor, "#ABCDEF")!;
    expect(patched).toContain(`"tabColor": "#ABCDEF"`);
    expect(patched).not.toContain("#111111");
    expect(patched.match(/tabColor/g)).toHaveLength(1);
    expect(patched.split("\n").length).toBe(withColor.split("\n").length);
  });

  it("returns null when the colour is already set, so the file is not rewritten", () => {
    const once = setPowerShellTabColor(WITH_COMMENTS, "#2F5F87")!;
    expect(setPowerShellTabColor(once, "#2f5f87")).toBeNull();
  });

  it("prefers PowerShell 7 over Windows PowerShell", () => {
    const both = WITH_COMMENTS.replace(
      `            {\n                "commandline": "%SystemRoot%\\\\System32\\\\cmd.exe"`,
      `            {\n                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",\n                "name": "PowerShell",\n                "source": "Windows.Terminal.PowershellCore"\n            },\n            {\n                "commandline": "%SystemRoot%\\\\System32\\\\cmd.exe"`,
    );
    const patched = setPowerShellTabColor(both, "#00FF00")!;
    const coreIndex = patched.indexOf("574e775e");
    const colorIndex = patched.indexOf("tabColor");
    // The inserted key is the first member of the PowerShell 7 object, so it
    // lands just before that object's guid.
    expect(colorIndex).toBeLessThan(coreIndex);
    expect(colorIndex).toBeGreaterThan(patched.indexOf("Windows PowerShell"));
  });

  it("skips a hidden PowerShell profile", () => {
    const hidden = WITH_COMMENTS.replace(`"hidden": false,\n                "name": "Windows PowerShell"`, `"hidden": true,\n                "name": "Windows PowerShell"`);
    expect(setPowerShellTabColor(hidden, "#2F5F87")).toBeNull();
  });

  it("is not fooled by braces and quotes inside strings", () => {
    const tricky = `{
  "profiles": {
    "list": [
      { "name": "Decoy", "commandline": "wsl.exe -e sh -c '{ echo \\"powershell.exe\\"; }'", "guid": "{aaaaaaaa-0000-0000-0000-000000000000}" },
      { "name": "Windows PowerShell", "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}" }
    ]
  }
}`;
    const patched = setPowerShellTabColor(tricky, "#123456")!;
    // The decoy's `{ ... }` inside a shell string must not be read as an
    // object, and its quoted "powershell.exe" must not match the commandline
    // test - so the colour lands on the real profile, after the decoy.
    expect(patched.indexOf("tabColor")).toBeGreaterThan(patched.indexOf("Decoy"));
    expect(patched).toContain(`"tabColor": "#123456"`);
    expect(patched).toContain(`"name": "Windows PowerShell"`);
    expect(patched.match(/tabColor/g)).toHaveLength(1);
  });

  it("handles the older schema where profiles is itself the array", () => {
    const older = `{
  "profiles": [
    { "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}", "name": "Windows PowerShell" }
  ]
}`;
    expect(setPowerShellTabColor(older, "#654321")).toContain(`"tabColor": "#654321"`);
  });

  it("matches on commandline when there is no guid, source or known name", () => {
    const byCommandline = `{
  "profiles": { "list": [ { "name": "My Shell", "commandline": "C:\\\\Program Files\\\\PowerShell\\\\7\\\\pwsh.exe -nologo" } ] }
}`;
    expect(setPowerShellTabColor(byCommandline, "#0A0B0C")).toContain(`"tabColor": "#0A0B0C"`);
  });

  it("returns null when there is no PowerShell profile at all", () => {
    const none = `{
  "profiles": { "list": [ { "name": "Command Prompt", "commandline": "cmd.exe" } ] }
}`;
    expect(setPowerShellTabColor(none, "#2F5F87")).toBeNull();
  });

  it("returns null for a file with no profiles key, an empty file, or junk", () => {
    expect(setPowerShellTabColor(`{ "schemes": [] }`, "#2F5F87")).toBeNull();
    expect(setPowerShellTabColor("", "#2F5F87")).toBeNull();
    expect(setPowerShellTabColor("not json at all", "#2F5F87")).toBeNull();
  });

  it("copes with a trailing comma after the last profile", () => {
    const trailing = `{
  "profiles": { "list": [
    { "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}", "name": "Windows PowerShell" },
  ] }
}`;
    expect(setPowerShellTabColor(trailing, "#2F5F87")).toContain(`"tabColor": "#2F5F87"`);
  });

  it("survives a block comment between members", () => {
    const blocky = `{
  "profiles": { "list": [
    { /* the shell */ "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}", "name": "Windows PowerShell" }
  ] }
}`;
    const patched = setPowerShellTabColor(blocky, "#2F5F87")!;
    expect(patched).toContain("/* the shell */");
    expect(patched).toContain(`"tabColor": "#2F5F87"`);
  });
});

describe("normalizeHex", () => {
  it("uppercases and adds the hash", () => {
    expect(normalizeHex("2f5f87")).toBe("#2F5F87");
    expect(normalizeHex("#abcdef")).toBe("#ABCDEF");
  });

  it("rejects anything that is not six hex digits", () => {
    for (const bad of ["#fff", "#GGGGGG", "rgb(1,2,3)", "", "#12345678"]) {
      expect(() => normalizeHex(bad)).toThrow();
    }
  });
});
