import os from "os";
import path from "path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import type { ThemeActionContext } from "../desktop-theme-actions";

const STABLE_PATH = "C:\\Users\\adeline\\AppData\\Local\\Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\settings.json";
const PREVIEW_PATH = "C:\\Users\\adeline\\AppData\\Local\\Packages\\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\\LocalState\\settings.json";
// Note the space - this is why the read protocol base64s the path.
const UNPACKAGED_PATH = "C:\\Users\\adeline\\AppData\\Local\\Microsoft\\Windows Terminal\\settings.json";

const SETTINGS = `{
    // generated by Windows Terminal
    "profiles": {
        "list": [
            {
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell"
            }
        ]
    }
}`;

const runManagedComputerSsh = vi.fn();

function context(hex = "#2F5F87"): ThemeActionContext {
  return {
    assetId: "wallpaper_00000000-0000-0000-0000-000000000001",
    computer: {
      id: "ununhexium",
      name: "Ununhexium",
      platform: "windows",
      sshKeyPath: path.join(os.tmpdir(), "nova-test-key"),
    } as unknown as ThemeActionContext["computer"],
    highlight: { fallback: false, hex, hsl: { h: 207, l: 0.36, s: 0.48 }, rgb: { b: 135, g: 95, r: 47 } },
    remoteFileName: "nova-wallpaper-test.png",
    variant: "dark",
  };
}

/** The PowerShell script inside a `-EncodedCommand` argument. */
function decodeCommand(command: string) {
  const encoded = command.slice(command.indexOf("-EncodedCommand ") + "-EncodedCommand ".length);
  return Buffer.from(encoded, "base64").toString("utf16le");
}

/** What the remote read returns: one base64 path + base64 bytes per line. */
function readReply(files: Array<{ bom?: boolean; content: string; path: string }>) {
  const lines = files.map((file) => {
    const bytes = Buffer.concat([
      file.bom ? Buffer.from([0xef, 0xbb, 0xbf]) : Buffer.alloc(0),
      Buffer.from(file.content, "utf8"),
    ]);
    return `NOVA-FILE ${Buffer.from(file.path, "utf8").toString("base64")} ${bytes.toString("base64")}`;
  });
  // Windows emits CRLF and a trailing newline.
  return { stderr: "", stdout: `${lines.join("\r\n")}\r\n` };
}

/** Re-run the splice the way the remote script would. */
function replaySplice(script: string, original: string) {
  const match = script.match(/Substring\(0, (\d+)\) \+ \$insert \+ \$text\.Substring\((\d+)\)/)!;
  const insert = Buffer.from(script.match(/FromBase64String\('([^']+)'\)/)![1], "base64").toString("utf8");
  return original.slice(0, Number(match[1])) + insert + original.slice(Number(match[2]));
}

async function importAction() {
  vi.resetModules();
  vi.doMock("../managed-computers", async () => {
    const actual = await vi.importActual<typeof import("../managed-computers")>("../managed-computers");
    return { ...actual, runManagedComputerSsh };
  });
  return (await import("./windows-terminal")).windowsTerminalAction;
}

beforeEach(() => {
  runManagedComputerSsh.mockReset();
});

afterEach(() => {
  vi.restoreAllMocks();
  vi.resetModules();
});

describe("windowsTerminalAction", () => {
  it("patches EVERY installed Terminal, not just the first", async () => {
    const action = await importAction();
    // Stable and Preview are routinely installed side by side, and the one
    // actually in use is not the one that sorts first. Taking only the first
    // wrote to a file nothing was reading.
    runManagedComputerSsh
      .mockResolvedValueOnce(readReply([
        { content: SETTINGS, path: STABLE_PATH },
        { content: SETTINGS, path: PREVIEW_PATH },
      ]))
      .mockResolvedValue({ stderr: "", stdout: "" });

    await action.run(context());

    const writes = runManagedComputerSsh.mock.calls.slice(1).map(([, command]) => decodeCommand(command));
    expect(writes).toHaveLength(2);
    expect(writes[0]).toContain(JSON.stringify(STABLE_PATH));
    expect(writes[1]).toContain(JSON.stringify(PREVIEW_PATH));
  });

  it("applies the splice, taking a one-time backup", async () => {
    const action = await importAction();
    runManagedComputerSsh
      .mockResolvedValueOnce(readReply([{ content: SETTINGS, path: STABLE_PATH }]))
      .mockResolvedValue({ stderr: "", stdout: "" });

    await action.run(context("#2F5F87"));

    expect(runManagedComputerSsh).toHaveBeenCalledTimes(2);
    const write = decodeCommand(runManagedComputerSsh.mock.calls[1][1]);
    expect(write).toContain(".nova-backup");
    expect(write).toContain("if (-not (Test-Path -LiteralPath $backup))");
    // Refuse an edit computed against a file that has since changed.
    expect(write).toContain(`if ($text.Length -ne ${SETTINGS.length})`);

    const result = replaySplice(write, SETTINGS);
    expect(result).toContain(`"tabColor": "#2F5F87"`);
    expect(result).toContain("// generated by Windows Terminal");
    expect(result).toContain(`"name": "Windows PowerShell"`);
  });

  it("replaces a tab colour that was already set by hand", async () => {
    const action = await importAction();
    const byHand = SETTINGS.replace(
      `"name": "Windows PowerShell"`,
      `"name": "Windows PowerShell",\n                "tabColor": "#58EA51"`,
    );
    runManagedComputerSsh
      .mockResolvedValueOnce(readReply([{ content: byHand, path: STABLE_PATH }]))
      .mockResolvedValue({ stderr: "", stdout: "" });

    await action.run(context("#77314D"));

    const result = replaySplice(decodeCommand(runManagedComputerSsh.mock.calls[1][1]), byHand);
    expect(result).toContain(`"tabColor": "#77314D"`);
    expect(result).not.toContain("#58EA51");
    expect(result.match(/tabColor/g)).toHaveLength(1);
  });

  it("decodes a path containing spaces", async () => {
    const action = await importAction();
    runManagedComputerSsh
      .mockResolvedValueOnce(readReply([{ content: SETTINGS, path: UNPACKAGED_PATH }]))
      .mockResolvedValue({ stderr: "", stdout: "" });

    await action.run(context());
    expect(decodeCommand(runManagedComputerSsh.mock.calls[1][1])).toContain(JSON.stringify(UNPACKAGED_PATH));
  });

  it("preserves a BOM, and keeps offsets aligned with the BOM stripped", async () => {
    const action = await importAction();
    runManagedComputerSsh
      .mockResolvedValueOnce(readReply([{ bom: true, content: SETTINGS, path: STABLE_PATH }]))
      .mockResolvedValue({ stderr: "", stdout: "" });

    await action.run(context());

    const write = decodeCommand(runManagedComputerSsh.mock.calls[1][1]);
    expect(write).toContain("New-Object Text.UTF8Encoding($true)");
    // The length check must be against the BOM-stripped text, since that is
    // what ReadAllText gives the far side.
    expect(write).toContain(`if ($text.Length -ne ${SETTINGS.length})`);
    expect(replaySplice(write, SETTINGS)).toContain(`"tabColor"`);
  });

  it("writes no BOM when the file had none", async () => {
    const action = await importAction();
    runManagedComputerSsh
      .mockResolvedValueOnce(readReply([{ content: SETTINGS, path: STABLE_PATH }]))
      .mockResolvedValue({ stderr: "", stdout: "" });

    await action.run(context());
    expect(decodeCommand(runManagedComputerSsh.mock.calls[1][1])).toContain("New-Object Text.UTF8Encoding($false)");
  });

  it("does not write when the colour is already set", async () => {
    const action = await importAction();
    const already = SETTINGS.replace(
      `"name": "Windows PowerShell"`,
      `"name": "Windows PowerShell",\n                "tabColor": "#2F5F87"`,
    );
    runManagedComputerSsh.mockResolvedValueOnce(readReply([{ content: already, path: STABLE_PATH }]));

    await action.run(context("#2F5F87"));

    // Writing is what makes Terminal reload; a reload nobody asked for is a
    // visible flicker in every open window.
    expect(runManagedComputerSsh).toHaveBeenCalledTimes(1);
  });

  it("still updates the other installs when one is already correct", async () => {
    const action = await importAction();
    const already = SETTINGS.replace(
      `"name": "Windows PowerShell"`,
      `"name": "Windows PowerShell",\n                "tabColor": "#2F5F87"`,
    );
    runManagedComputerSsh
      .mockResolvedValueOnce(readReply([
        { content: already, path: STABLE_PATH },
        { content: SETTINGS, path: PREVIEW_PATH },
      ]))
      .mockResolvedValue({ stderr: "", stdout: "" });

    await action.run(context("#2F5F87"));

    expect(runManagedComputerSsh).toHaveBeenCalledTimes(2);
    expect(decodeCommand(runManagedComputerSsh.mock.calls[1][1])).toContain(JSON.stringify(PREVIEW_PATH));
  });

  it("keeps going when one install throws", async () => {
    const action = await importAction();
    const errors = vi.spyOn(console, "error").mockImplementation(() => {});
    runManagedComputerSsh
      .mockResolvedValueOnce(readReply([
        { content: SETTINGS, path: STABLE_PATH },
        { content: SETTINGS, path: PREVIEW_PATH },
      ]))
      .mockRejectedValueOnce(new Error("access denied"))
      .mockResolvedValue({ stderr: "", stdout: "" });

    await expect(action.run(context())).resolves.toBeUndefined();

    // The one that matters may well be the one after the failure.
    expect(runManagedComputerSsh).toHaveBeenCalledTimes(3);
    expect(decodeCommand(runManagedComputerSsh.mock.calls[2][1])).toContain(JSON.stringify(PREVIEW_PATH));
    expect(errors).toHaveBeenCalled();
  });

  it("falls back to the whitespace nudge when there is no PowerShell profile", async () => {
    const action = await importAction();
    const noPowerShell = `{ "profiles": { "list": [ { "name": "Command Prompt", "commandline": "cmd.exe" } ] } }`;
    runManagedComputerSsh
      .mockResolvedValueOnce(readReply([{ content: noPowerShell, path: STABLE_PATH }]))
      .mockResolvedValue({ stderr: "", stdout: "" });

    await action.run(context());

    expect(runManagedComputerSsh).toHaveBeenCalledTimes(2);
    const nudge = decodeCommand(runManagedComputerSsh.mock.calls[1][1]);
    expect(nudge).toContain("WriteAllBytes");
    expect(nudge).toContain(JSON.stringify(STABLE_PATH));
    expect(nudge).not.toContain("FromBase64String");
  });

  it("does nothing when Terminal is not installed", async () => {
    const action = await importAction();
    runManagedComputerSsh.mockResolvedValueOnce({ stderr: "", stdout: "" });

    await action.run(context());
    expect(runManagedComputerSsh).toHaveBeenCalledTimes(1);
  });

  it("refuses to rewrite an implausibly large settings file", async () => {
    const action = await importAction();
    const errors = vi.spyOn(console, "error").mockImplementation(() => {});
    const huge = SETTINGS.replace("// generated by Windows Terminal", `// ${"x".repeat(70 * 1024)}`);
    runManagedComputerSsh.mockResolvedValueOnce(readReply([{ content: huge, path: STABLE_PATH }]));

    await action.run(context());

    expect(runManagedComputerSsh).toHaveBeenCalledTimes(1);
    expect(errors).toHaveBeenCalled();
  });

  it("never sends the file itself, so the command line cannot overflow", async () => {
    const action = await importAction();
    // cmd.exe caps the command line at 8191 characters; base64'ing a file this
    // size into the command would be several times that.
    const big = SETTINGS.replace("// generated by Windows Terminal", `// ${"padding ".repeat(1200)}`);
    expect(big.length).toBeGreaterThan(8191);

    runManagedComputerSsh
      .mockResolvedValueOnce(readReply([{ content: big, path: STABLE_PATH }]))
      .mockResolvedValue({ stderr: "", stdout: "" });

    await action.run(context());

    // The read reply carries the file, but the commands we send must not.
    for (const [, command] of runManagedComputerSsh.mock.calls) {
      expect(command.length).toBeLessThan(8000);
    }
  });

  it("asks for all three settings locations on the read", async () => {
    const action = await importAction();
    runManagedComputerSsh.mockResolvedValueOnce({ stderr: "", stdout: "" });

    await action.run(context());
    const read = decodeCommand(runManagedComputerSsh.mock.calls[0][1]);
    expect(read).toContain("Microsoft.WindowsTerminal_8wekyb3d8bbwe");
    expect(read).toContain("Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe");
    expect(read).toContain("Microsoft\\Windows Terminal\\settings.json");
  });

  it("signs on the highlight colour, so a recolour re-fires it", async () => {
    const action = await importAction();
    expect(action.signature(context("#111111"))).not.toBe(action.signature(context("#222222")));
  });
});
