import os from "os";
import path from "path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import type { ThemeActionContext } from "../desktop-theme-actions";

const SETTINGS_PATH = "C:\\Users\\adeline\\AppData\\Local\\Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\settings.json";

const SETTINGS = `{
    // generated by Windows Terminal
    "profiles": {
        "list": [
            {
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell"
            }
        ]
    }
}`;

const runManagedComputerSsh = vi.fn();

function context(hex = "#2F5F87"): ThemeActionContext {
  return {
    assetId: "wallpaper_00000000-0000-0000-0000-000000000001",
    computer: {
      id: "ununhexium",
      name: "Ununhexium",
      platform: "windows",
      sshKeyPath: path.join(os.tmpdir(), "nova-test-key"),
    } as unknown as ThemeActionContext["computer"],
    highlight: { fallback: false, hex, hsl: { h: 207, l: 0.36, s: 0.48 }, rgb: { b: 135, g: 95, r: 47 } },
    remoteFileName: "nova-wallpaper-test.png",
    variant: "dark",
  };
}

/** The PowerShell script inside a `-EncodedCommand` argument. */
function decodeCommand(command: string) {
  const encoded = command.slice(command.indexOf("-EncodedCommand ") + "-EncodedCommand ".length);
  return Buffer.from(encoded, "base64").toString("utf16le");
}

/**
 * What the remote read actually returns. Windows emits CRLF - getting this
 * wrong once made the whole action silently no-op on the real machine, so both
 * endings are exercised.
 */
function readReply(content: string, settingsPath = SETTINGS_PATH, eol: "\n" | "\r\n" = "\r\n") {
  return { stderr: "", stdout: `${settingsPath}${eol}---${eol}${content}${eol}` };
}

async function importAction() {
  vi.resetModules();
  vi.doMock("../managed-computers", async () => {
    const actual = await vi.importActual<typeof import("../managed-computers")>("../managed-computers");
    return { ...actual, runManagedComputerSsh };
  });
  return (await import("./windows-terminal")).windowsTerminalAction;
}

beforeEach(() => {
  runManagedComputerSsh.mockReset();
});

afterEach(() => {
  vi.restoreAllMocks();
  vi.resetModules();
});

describe("windowsTerminalAction", () => {
  it("applies the splice remotely, taking a one-time backup", async () => {
    const action = await importAction();
    runManagedComputerSsh
      .mockResolvedValueOnce(readReply(SETTINGS))
      .mockResolvedValueOnce({ stderr: "", stdout: "" });

    await action.run(context("#2F5F87"));

    expect(runManagedComputerSsh).toHaveBeenCalledTimes(2);
    const write = decodeCommand(runManagedComputerSsh.mock.calls[1][1]);
    expect(write).toContain(".nova-backup");
    expect(write).toContain("if (-not (Test-Path -LiteralPath $backup))");
    // Length check against the file as it was read, so a file that changed
    // underneath is refused rather than spliced at the wrong offset.
    expect(write).toContain(`if ($text.Length -ne ${SETTINGS.length})`);
    // BOM state is preserved rather than assumed.
    expect(write).toContain("New-Object Text.UTF8Encoding($bom)");

    // Replay the splice the way the remote side would, and check the result.
    const [, offset, length] = write.match(/Substring\(0, (\d+)\) \+ \$insert \+ \$text\.Substring\((\d+)\)/)!.map(Number);
    const insert = Buffer.from(write.match(/FromBase64String\('([^']+)'\)/)![1], "base64").toString("utf8");
    const result = SETTINGS.slice(0, offset) + insert + SETTINGS.slice(length);
    expect(result).toContain(`"tabColor": "#2F5F87"`);
    expect(result).toContain("// generated by Windows Terminal");
    expect(result).toContain(`"name": "Windows PowerShell"`);
  });

  it("never sends the file itself, so the command line cannot overflow", async () => {
    const action = await importAction();
    // A realistically large settings file. cmd.exe caps the command line at
    // 8191 characters; base64'ing this one would be several times that.
    const big = SETTINGS.replace("// generated by Windows Terminal", `// ${"padding ".repeat(1200)}`);
    expect(big.length).toBeGreaterThan(8191);

    runManagedComputerSsh
      .mockResolvedValueOnce(readReply(big))
      .mockResolvedValueOnce({ stderr: "", stdout: "" });

    await action.run(context());

    for (const [, command] of runManagedComputerSsh.mock.calls) {
      expect(command.length).toBeLessThan(8000);
    }
  });

  it("targets the path the read reported", async () => {
    const action = await importAction();
    const unpackaged = "C:\\Users\\adeline\\AppData\\Local\\Microsoft\\Windows Terminal\\settings.json";
    runManagedComputerSsh
      .mockResolvedValueOnce(readReply(SETTINGS, unpackaged))
      .mockResolvedValueOnce({ stderr: "", stdout: "" });

    await action.run(context());
    expect(decodeCommand(runManagedComputerSsh.mock.calls[1][1])).toContain(JSON.stringify(unpackaged));
  });

  it("does not write when the colour is already set", async () => {
    const action = await importAction();
    const already = SETTINGS.replace(`"name": "Windows PowerShell"`, `"name": "Windows PowerShell",\n                "tabColor": "#2F5F87"`);
    runManagedComputerSsh.mockResolvedValueOnce(readReply(already));

    await action.run(context("#2F5F87"));

    // Writing is what makes Terminal reload; a reload nobody asked for is a
    // visible flicker in every open window.
    expect(runManagedComputerSsh).toHaveBeenCalledTimes(1);
  });

  it("falls back to the whitespace nudge when there is no PowerShell profile", async () => {
    const action = await importAction();
    const noPowerShell = `{ "profiles": { "list": [ { "name": "Command Prompt", "commandline": "cmd.exe" } ] } }`;
    runManagedComputerSsh
      .mockResolvedValueOnce(readReply(noPowerShell))
      .mockResolvedValueOnce({ stderr: "", stdout: "" });

    await action.run(context());

    expect(runManagedComputerSsh).toHaveBeenCalledTimes(2);
    const nudge = decodeCommand(runManagedComputerSsh.mock.calls[1][1]);
    expect(nudge).toContain("WriteAllBytes");
    expect(nudge).not.toContain("FromBase64String");
  });

  it("does nothing when Terminal is not installed", async () => {
    const action = await importAction();
    runManagedComputerSsh.mockResolvedValueOnce({ stderr: "", stdout: "NOVA-NO-SETTINGS\n" });

    await action.run(context());
    expect(runManagedComputerSsh).toHaveBeenCalledTimes(1);
  });

  it("refuses to rewrite an implausibly large settings file", async () => {
    const action = await importAction();
    const errors = vi.spyOn(console, "error").mockImplementation(() => {});
    const huge = SETTINGS.replace("// generated by Windows Terminal", `// ${"x".repeat(70 * 1024)}`);
    runManagedComputerSsh.mockResolvedValueOnce(readReply(huge));

    await action.run(context());

    expect(runManagedComputerSsh).toHaveBeenCalledTimes(1);
    expect(errors).toHaveBeenCalled();
  });

  it("asks for all three settings locations on the read", async () => {
    const action = await importAction();
    runManagedComputerSsh.mockResolvedValueOnce({ stderr: "", stdout: "NOVA-NO-SETTINGS\n" });

    await action.run(context());
    const read = decodeCommand(runManagedComputerSsh.mock.calls[0][1]);
    expect(read).toContain("Microsoft.WindowsTerminal_8wekyb3d8bbwe");
    expect(read).toContain("Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe");
    expect(read).toContain("Microsoft\\Windows Terminal\\settings.json");
  });

  it.each([["CRLF", "\r\n"], ["LF", "\n"]] as const)("parses a %s read reply", async (_label, eol) => {
    const action = await importAction();
    runManagedComputerSsh
      .mockResolvedValueOnce(readReply(SETTINGS, SETTINGS_PATH, eol))
      .mockResolvedValueOnce({ stderr: "", stdout: "" });

    await action.run(context());

    expect(runManagedComputerSsh).toHaveBeenCalledTimes(2);
    const write = decodeCommand(runManagedComputerSsh.mock.calls[1][1]);
    const insert = Buffer.from(write.match(/FromBase64String\('([^']+)'\)/)![1], "base64").toString("utf8");
    expect(insert).toContain(`"tabColor": "#2F5F87"`);
    // The path line must not carry a stray carriage return into the write.
    expect(write).toContain(JSON.stringify(SETTINGS_PATH));
  });

  it("signs on the highlight colour, so a recolour re-fires it", async () => {
    const action = await importAction();
    expect(action.signature(context("#111111"))).not.toBe(action.signature(context("#222222")));
  });
});
